name: Run extra tests on issue / pull-request comments

on:
  issue_comment:
    types:
      - created
      
jobs:

  scaled_sim:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: ubuntu-latest
      keyword: scaled-sim
      commands: |
        set -x
        python --version
        uname -a
        lsb_release -a
        python -m cProfile src/scripts/run_sim.py
      description: Scale run of model
      use-application-token: true
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}
      
  scaled_sim_github_token:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: ubuntu-latest
      keyword: scaled-sim-github-token
      commands: |
        set -x
        python --version
        uname -a
        lsb_release -a
        python -m cProfile src/scripts/run_sim.py
      description: Scale run of model
      
  multiple_seed_tests:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: ubuntu-latest
      keyword: multiple-seed-tests
      commands: |
        set -x
        python --version
        uname -a
        lsb_release -a
        python -m cProfile src/scripts/run_sim.py
        python -m cProfile src/scripts/run_sim.py
        python -m cProfile src/scripts/run_sim.py
        python -m cProfile src/scripts/run_sim.py
        python -m cProfile src/scripts/run_sim.py
        python -m cProfile src/scripts/run_sim.py
        python -m cProfile src/scripts/run_sim.py
        python -m cProfile src/scripts/run_sim.py
        python -m cProfile src/scripts/run_sim.py
        python -m cProfile src/scripts/run_sim.py
      description: Run of tests over multiple seeds
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}

  array_runs_on:
    uses: ./.github/workflows/run-on-comment.yml
    with:
      runs-on: '["ubuntu-latest"]'
      keyword: array-runs-on
      commands: |
        set -x
        python --version
        uname -a
        lsb_release -a
        python -m cProfile src/scripts/run_sim.py
      description: Running with array runs-on input
      use-application-token: true
    secrets:
      application-id: ${{ secrets.COMMENT_BOT_APP_ID }}
      application-private-key: ${{ secrets.COMMENT_BOT_APP_PRIVATE_KEY }}
