name: Run extra tests on PR comments

on:
  issue_comment:
    types:
      - created
      
jobs:

  scaled_sim:
    uses: ./.github/workflows/run-on-pr-comment.yml
    with:
      keyword: scaled-sim
      run_test: |
        python -m cProfile src/scripts/run_sim.py
      description: Scale run of model

