name: Run extra tests on PR comment

on:
  issue_comment:
    types:
      - created
      
jobs:

  run_model:
    uses: ./.github/workflows/run-on-pr-comment.yml
    with:
      keyword: scaled-sim
      run_test: |
        python -m cProfile src/scripts/run_sim.py
        echo "Done"
      description: Scale run of model

