name: Run extra tests on pull-request comments

on:
  issue_comment:
    types:
      - created
      
jobs:

  scaled_sim:
    uses: ./.github/workflows/run-on-pr-comment.yml
    with:
      runs-on: ubuntu-latest
      keyword: scaled-sim
      commands: python -m cProfile src/scripts/run_sim.py
      description: Scale run of model
